BTN_SEP = 10

BTN_LEVELS_WIDTH = 100
BTN_LEVELS_HEIGHT = 50

LEVELS_COUNT = 10
BTN_LEVEL_WIDTH = 70
BTN_LEVEL_HEIGHT = 50
BTN_LEVEL_START_HEIGHT = BTN_SEP * 2 + BTN_LEVELS_HEIGHT
BTN_LEVEL_IN_ROW_COUNT = 4

BTN_STATS_WIDTH = 100
BTN_STATS_HEIGHT = 50
BTN_STATS_START_WIDTH = BTN_SEP * 3 + (
        BTN_SEP + BTN_LEVEL_WIDTH) * BTN_LEVEL_IN_ROW_COUNT
BTN_STATS_START_HEIGHT = BTN_SEP

TEXT_STATS_WIDTH = 300
TEXT_STATS_HEIGHT = 100
TEXT_STATS_START_WIDTH = BTN_STATS_START_WIDTH
TEXT_STATS_START_HEIGHT = BTN_STATS_START_HEIGHT + BTN_STATS_HEIGHT + BTN_SEP

BTN_START_LEVEL_WIDTH = 100
BTN_START_LEVEL_HEIGHT = 50
BTN_START_LEVEL_START_WIDTH = BTN_SEP
BTN_START_LEVEL_START_HEIGHT = BTN_LEVEL_START_HEIGHT + BTN_SEP * 2 + (
        BTN_SEP + BTN_LEVEL_HEIGHT) * ((LEVELS_COUNT + BTN_LEVEL_IN_ROW_COUNT - 1) //
                                       BTN_LEVEL_IN_ROW_COUNT)

BTN_FINISH_LEVEL_WIDTH = 100
BTN_FINISH_LEVEL_HEIGHT = 50
BTN_FINISH_LEVEL_START_WIDTH = BTN_SEP * 4 + BTN_START_LEVEL_WIDTH
BTN_FINISH_LEVEL_START_HEIGHT = BTN_LEVEL_START_HEIGHT + BTN_SEP * 2 + (
        BTN_SEP + BTN_LEVEL_HEIGHT) * ((LEVELS_COUNT + BTN_LEVEL_IN_ROW_COUNT - 1) //
                                       BTN_LEVEL_IN_ROW_COUNT)

LEVEL_TEXT_WIDTH = 400
LEVEL_TEXT_HEIGHT = 25
LEVEL_TEXT_START_WIDTH = BTN_SEP + 7
LEVEL_TEXT_START_HEIGHT = (BTN_FINISH_LEVEL_START_HEIGHT + BTN_FINISH_LEVEL_HEIGHT +
                           BTN_SEP)

LINE_EDIT_INPUT_TEXT_WIDTH = 190
LINE_EDIT_INPUT_TEXT_HEIGHT = 25
LINE_EDIT_INPUT_TEXT_START_WIDTH = LEVEL_TEXT_START_WIDTH
LINE_EDIT_INPUT_TEXT_START_HEIGHT = (LEVEL_TEXT_START_HEIGHT + LEVEL_TEXT_HEIGHT)

MAX_TIME = 100000000
